apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ns-reader-role
  namespace: ns-watcher
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ns-reader-cluster-binding
subjects:
- kind: ServiceAccount
  name: ns-watcher-account
  namespace: ns-watcher
roleRef:
  kind: ClusterRole
  name: ns-reader-role
  apiGroup: rbac.authorization.k8s.io
