apiVersion: v1
kind: ServiceAccount
metadata:
  name: ns-watcher-account
  namespace: ns-watcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ns-reader-role
  namespace: ns-watcher
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ns-reader-cluster-binding
subjects:
- kind: ServiceAccount
  name: ns-watcher-account
  namespace: ns-watcher
roleRef:
  kind: ClusterRole
  name: ns-reader-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-label-operator
  namespace: ns-watcher
  labels:
    app: ns-label-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ns-label-operator
  template:
    metadata:
      labels:
        app: ns-label-operator
    spec:
      restartPolicy: Always
      serviceAccountName: ns-watcher-account
      containers:
      - name: watch
        image: ghcr.io/mchmarny/ns-label-operator:v0.4.5 # latest stable
        env:
        - name: TRIGGER_LABEL
          valueFrom:
            configMapKeyRef:
              name: trigger-label
              key: label
        - name: DEBUG
          value: "true"
        - name: LOG_TO_JSON
          value: "true"
        - name: CONFIG_DIR
          value: "/config"
        volumeMounts:
        - name: "config"
          mountPath: "/config"
      volumes:
        - name: "config"
          configMap:
            name: "trigger-config"
      

